services:
  warehouse:
    image: postgres:latest
    container_name: warehouse
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ,"-d","${POSTGRES_DB}"]
      interval: 5s
      retries: 5
    restart: always
    ports:
      - "5432:5432"
  data_job:
    image: pipeline_infra
    container_name: pipeline_cont
    build:
      context: ./
      dockerfile: ./container/Dockerfile
    volumes:
      - ./:/code
    environment:
      WAREHOUSE_USER: ${POSTGRES_USER}
      WAREHOUSE_PASSWORD: ${POSTGRES_PASSWORD}
      WAREHOUSE_DB: ${POSTGRES_DB}
      WAREHOUSE_HOST: ${POSTGRES_HOST}
      WARREHOUSE_PORT: ${POSTGRES_PORT}
